### ISSUE TITLE
How to install the API?

### ISSUE THREAD

**Issue by asmab89** [moustaphastar/bakery-management-app#16]
Hi, would you please provide how to run the application? 
Installing
*Clone the project git clone https://github.com/moustaphastar/bakery-management-app.git or download the code.
*Open the project with your IDE and (?)

**Comment by moustaphastar** [comment]
Hi @asmab89, thank you for your interest for the project. 

I am so sorry to say that I have not completed the project yet. That is just a startup and there are many missing parts. I will complete it as soon as possible. But I have updated the readme file. If that does not work for you or if you have any other questions or ideas, please let me know.

Thanks.

**Comment by asmab89** [comment]
Hi, thank you for your quick response and clarifications.

**Comment by moustaphastar** [comment]
You are welcome. Executing `gradle build` and `gradle bootRun` will start the application (or `gradlew ...`). 

I have added OpenAPI and swagger ui as well as some code to start a browser with the default swagger-ui. While using swagger-ui you need to provide a garphql json payload here is an example:

![image](https://user-images.githubusercontent.com/38510483/108852434-a83e6c80-75f6-11eb-9dfa-fdab8881bd6a.png)
)

But it's much more easier with an app like [GraphQL Playground](https://github.com/graphql/graphql-playground):

![graphql_playground_sample](https://user-images.githubusercontent.com/38510483/108853620-ff910c80-75f7-11eb-8ae7-4d8cc05b31d9.png)

Also, if you change the code, be sure to execute `gradle check` to see and correct if there is any [checkStyle](https://checkstyle.org/) rule voilations.
